[settings]
experimental = true
legacy_version_file = false

[tools]
usage = "latest"
terraform = "latest"
chezmoi = "latest"
go = "1.24.2"
eza = "latest"
bitwarden = "latest"
pre-commit = "latest"
fzf = "latest"
kubectl = "latest"
go-jsonnet = "latest"
node = "latest"
just = "latest"
cosign = "latest"
