[settings]
experimental = true
legacy_version_file = false

[tools]
usage = "latest"
terraform = "latest"
chezmoi = "latest"
go = "latest"
eza = "latest"
bitwarden = "latest"
pre-commit = "latest"
fzf = "latest"
